<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static/models/remote.glb -t
-->

<script lang="ts">
	import type * as THREE from 'three';

	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { asset } from '$app/paths';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	type GLTFResult = {
		nodes: {
			remote: THREE.Mesh;
		};
		materials: {
			DefaultMaterial: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>(asset('/models/remote.glb'));
</script>

<T.Group bind:ref dispose={false} {...props} position={[2, 1, 0]} rotation={[0.2, 0, 0]}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh geometry={gltf.nodes.remote.geometry} material={gltf.materials.DefaultMaterial} />
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
